// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: sikuli/v1/sikuli.proto

package sikuliv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SikuliService_ListScreens_FullMethodName      = "/sikuli.v1.SikuliService/ListScreens"
	SikuliService_GetPrimaryScreen_FullMethodName = "/sikuli.v1.SikuliService/GetPrimaryScreen"
	SikuliService_CaptureScreen_FullMethodName    = "/sikuli.v1.SikuliService/CaptureScreen"
	SikuliService_Find_FullMethodName             = "/sikuli.v1.SikuliService/Find"
	SikuliService_FindAll_FullMethodName          = "/sikuli.v1.SikuliService/FindAll"
	SikuliService_FindOnScreen_FullMethodName     = "/sikuli.v1.SikuliService/FindOnScreen"
	SikuliService_ExistsOnScreen_FullMethodName   = "/sikuli.v1.SikuliService/ExistsOnScreen"
	SikuliService_WaitOnScreen_FullMethodName     = "/sikuli.v1.SikuliService/WaitOnScreen"
	SikuliService_ClickOnScreen_FullMethodName    = "/sikuli.v1.SikuliService/ClickOnScreen"
	SikuliService_ReadText_FullMethodName         = "/sikuli.v1.SikuliService/ReadText"
	SikuliService_FindText_FullMethodName         = "/sikuli.v1.SikuliService/FindText"
	SikuliService_MoveMouse_FullMethodName        = "/sikuli.v1.SikuliService/MoveMouse"
	SikuliService_Click_FullMethodName            = "/sikuli.v1.SikuliService/Click"
	SikuliService_TypeText_FullMethodName         = "/sikuli.v1.SikuliService/TypeText"
	SikuliService_PasteText_FullMethodName        = "/sikuli.v1.SikuliService/PasteText"
	SikuliService_Hotkey_FullMethodName           = "/sikuli.v1.SikuliService/Hotkey"
	SikuliService_MouseDown_FullMethodName        = "/sikuli.v1.SikuliService/MouseDown"
	SikuliService_MouseUp_FullMethodName          = "/sikuli.v1.SikuliService/MouseUp"
	SikuliService_KeyDown_FullMethodName          = "/sikuli.v1.SikuliService/KeyDown"
	SikuliService_KeyUp_FullMethodName            = "/sikuli.v1.SikuliService/KeyUp"
	SikuliService_ScrollWheel_FullMethodName      = "/sikuli.v1.SikuliService/ScrollWheel"
	SikuliService_ObserveAppear_FullMethodName    = "/sikuli.v1.SikuliService/ObserveAppear"
	SikuliService_ObserveVanish_FullMethodName    = "/sikuli.v1.SikuliService/ObserveVanish"
	SikuliService_ObserveChange_FullMethodName    = "/sikuli.v1.SikuliService/ObserveChange"
	SikuliService_OpenApp_FullMethodName          = "/sikuli.v1.SikuliService/OpenApp"
	SikuliService_FocusApp_FullMethodName         = "/sikuli.v1.SikuliService/FocusApp"
	SikuliService_CloseApp_FullMethodName         = "/sikuli.v1.SikuliService/CloseApp"
	SikuliService_IsAppRunning_FullMethodName     = "/sikuli.v1.SikuliService/IsAppRunning"
	SikuliService_ListWindows_FullMethodName      = "/sikuli.v1.SikuliService/ListWindows"
	SikuliService_FindWindows_FullMethodName      = "/sikuli.v1.SikuliService/FindWindows"
	SikuliService_GetWindow_FullMethodName        = "/sikuli.v1.SikuliService/GetWindow"
	SikuliService_GetFocusedWindow_FullMethodName = "/sikuli.v1.SikuliService/GetFocusedWindow"
)

// SikuliServiceClient is the client API for SikuliService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SikuliServiceClient interface {
	ListScreens(ctx context.Context, in *ListScreensRequest, opts ...grpc.CallOption) (*ListScreensResponse, error)
	GetPrimaryScreen(ctx context.Context, in *GetPrimaryScreenRequest, opts ...grpc.CallOption) (*GetPrimaryScreenResponse, error)
	CaptureScreen(ctx context.Context, in *CaptureScreenRequest, opts ...grpc.CallOption) (*CaptureScreenResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindAll(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindAllResponse, error)
	FindOnScreen(ctx context.Context, in *FindOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error)
	ExistsOnScreen(ctx context.Context, in *ExistsOnScreenRequest, opts ...grpc.CallOption) (*ExistsOnScreenResponse, error)
	WaitOnScreen(ctx context.Context, in *WaitOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error)
	ClickOnScreen(ctx context.Context, in *ClickOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error)
	ReadText(ctx context.Context, in *ReadTextRequest, opts ...grpc.CallOption) (*ReadTextResponse, error)
	FindText(ctx context.Context, in *FindTextRequest, opts ...grpc.CallOption) (*FindTextResponse, error)
	MoveMouse(ctx context.Context, in *MoveMouseRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	PasteText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Hotkey(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	MouseDown(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	MouseUp(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	KeyDown(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	KeyUp(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ScrollWheel(ctx context.Context, in *ScrollWheelRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ObserveAppear(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	ObserveVanish(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	ObserveChange(ctx context.Context, in *ObserveChangeRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	OpenApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	FocusApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	CloseApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	IsAppRunning(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*IsAppRunningResponse, error)
	ListWindows(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ListWindowsResponse, error)
	FindWindows(ctx context.Context, in *WindowQueryRequest, opts ...grpc.CallOption) (*ListWindowsResponse, error)
	GetWindow(ctx context.Context, in *WindowQueryRequest, opts ...grpc.CallOption) (*GetWindowResponse, error)
	GetFocusedWindow(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*GetWindowResponse, error)
}

type sikuliServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSikuliServiceClient(cc grpc.ClientConnInterface) SikuliServiceClient {
	return &sikuliServiceClient{cc}
}

func (c *sikuliServiceClient) ListScreens(ctx context.Context, in *ListScreensRequest, opts ...grpc.CallOption) (*ListScreensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScreensResponse)
	err := c.cc.Invoke(ctx, SikuliService_ListScreens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) GetPrimaryScreen(ctx context.Context, in *GetPrimaryScreenRequest, opts ...grpc.CallOption) (*GetPrimaryScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrimaryScreenResponse)
	err := c.cc.Invoke(ctx, SikuliService_GetPrimaryScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) CaptureScreen(ctx context.Context, in *CaptureScreenRequest, opts ...grpc.CallOption) (*CaptureScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureScreenResponse)
	err := c.cc.Invoke(ctx, SikuliService_CaptureScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, SikuliService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) FindAll(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllResponse)
	err := c.cc.Invoke(ctx, SikuliService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) FindOnScreen(ctx context.Context, in *FindOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, SikuliService_FindOnScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ExistsOnScreen(ctx context.Context, in *ExistsOnScreenRequest, opts ...grpc.CallOption) (*ExistsOnScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsOnScreenResponse)
	err := c.cc.Invoke(ctx, SikuliService_ExistsOnScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) WaitOnScreen(ctx context.Context, in *WaitOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, SikuliService_WaitOnScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ClickOnScreen(ctx context.Context, in *ClickOnScreenRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, SikuliService_ClickOnScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ReadText(ctx context.Context, in *ReadTextRequest, opts ...grpc.CallOption) (*ReadTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTextResponse)
	err := c.cc.Invoke(ctx, SikuliService_ReadText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) FindText(ctx context.Context, in *FindTextRequest, opts ...grpc.CallOption) (*FindTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindTextResponse)
	err := c.cc.Invoke(ctx, SikuliService_FindText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) MoveMouse(ctx context.Context, in *MoveMouseRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_MoveMouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_TypeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) PasteText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_PasteText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) Hotkey(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_Hotkey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) MouseDown(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_MouseDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) MouseUp(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_MouseUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) KeyDown(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_KeyDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) KeyUp(ctx context.Context, in *HotkeyRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_KeyUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ScrollWheel(ctx context.Context, in *ScrollWheelRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_ScrollWheel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ObserveAppear(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, SikuliService_ObserveAppear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ObserveVanish(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, SikuliService_ObserveVanish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ObserveChange(ctx context.Context, in *ObserveChangeRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, SikuliService_ObserveChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) OpenApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_OpenApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) FocusApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_FocusApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) CloseApp(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, SikuliService_CloseApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) IsAppRunning(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*IsAppRunningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAppRunningResponse)
	err := c.cc.Invoke(ctx, SikuliService_IsAppRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) ListWindows(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*ListWindowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWindowsResponse)
	err := c.cc.Invoke(ctx, SikuliService_ListWindows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) FindWindows(ctx context.Context, in *WindowQueryRequest, opts ...grpc.CallOption) (*ListWindowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWindowsResponse)
	err := c.cc.Invoke(ctx, SikuliService_FindWindows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) GetWindow(ctx context.Context, in *WindowQueryRequest, opts ...grpc.CallOption) (*GetWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWindowResponse)
	err := c.cc.Invoke(ctx, SikuliService_GetWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sikuliServiceClient) GetFocusedWindow(ctx context.Context, in *AppActionRequest, opts ...grpc.CallOption) (*GetWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWindowResponse)
	err := c.cc.Invoke(ctx, SikuliService_GetFocusedWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SikuliServiceServer is the server API for SikuliService service.
// All implementations must embed UnimplementedSikuliServiceServer
// for forward compatibility.
type SikuliServiceServer interface {
	ListScreens(context.Context, *ListScreensRequest) (*ListScreensResponse, error)
	GetPrimaryScreen(context.Context, *GetPrimaryScreenRequest) (*GetPrimaryScreenResponse, error)
	CaptureScreen(context.Context, *CaptureScreenRequest) (*CaptureScreenResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	FindAll(context.Context, *FindRequest) (*FindAllResponse, error)
	FindOnScreen(context.Context, *FindOnScreenRequest) (*FindResponse, error)
	ExistsOnScreen(context.Context, *ExistsOnScreenRequest) (*ExistsOnScreenResponse, error)
	WaitOnScreen(context.Context, *WaitOnScreenRequest) (*FindResponse, error)
	ClickOnScreen(context.Context, *ClickOnScreenRequest) (*FindResponse, error)
	ReadText(context.Context, *ReadTextRequest) (*ReadTextResponse, error)
	FindText(context.Context, *FindTextRequest) (*FindTextResponse, error)
	MoveMouse(context.Context, *MoveMouseRequest) (*ActionResponse, error)
	Click(context.Context, *ClickRequest) (*ActionResponse, error)
	TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error)
	PasteText(context.Context, *TypeTextRequest) (*ActionResponse, error)
	Hotkey(context.Context, *HotkeyRequest) (*ActionResponse, error)
	MouseDown(context.Context, *ClickRequest) (*ActionResponse, error)
	MouseUp(context.Context, *ClickRequest) (*ActionResponse, error)
	KeyDown(context.Context, *HotkeyRequest) (*ActionResponse, error)
	KeyUp(context.Context, *HotkeyRequest) (*ActionResponse, error)
	ScrollWheel(context.Context, *ScrollWheelRequest) (*ActionResponse, error)
	ObserveAppear(context.Context, *ObserveRequest) (*ObserveResponse, error)
	ObserveVanish(context.Context, *ObserveRequest) (*ObserveResponse, error)
	ObserveChange(context.Context, *ObserveChangeRequest) (*ObserveResponse, error)
	OpenApp(context.Context, *AppActionRequest) (*ActionResponse, error)
	FocusApp(context.Context, *AppActionRequest) (*ActionResponse, error)
	CloseApp(context.Context, *AppActionRequest) (*ActionResponse, error)
	IsAppRunning(context.Context, *AppActionRequest) (*IsAppRunningResponse, error)
	ListWindows(context.Context, *AppActionRequest) (*ListWindowsResponse, error)
	FindWindows(context.Context, *WindowQueryRequest) (*ListWindowsResponse, error)
	GetWindow(context.Context, *WindowQueryRequest) (*GetWindowResponse, error)
	GetFocusedWindow(context.Context, *AppActionRequest) (*GetWindowResponse, error)
	mustEmbedUnimplementedSikuliServiceServer()
}

// UnimplementedSikuliServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSikuliServiceServer struct{}

func (UnimplementedSikuliServiceServer) ListScreens(context.Context, *ListScreensRequest) (*ListScreensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScreens not implemented")
}
func (UnimplementedSikuliServiceServer) GetPrimaryScreen(context.Context, *GetPrimaryScreenRequest) (*GetPrimaryScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrimaryScreen not implemented")
}
func (UnimplementedSikuliServiceServer) CaptureScreen(context.Context, *CaptureScreenRequest) (*CaptureScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureScreen not implemented")
}
func (UnimplementedSikuliServiceServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedSikuliServiceServer) FindAll(context.Context, *FindRequest) (*FindAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedSikuliServiceServer) FindOnScreen(context.Context, *FindOnScreenRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOnScreen not implemented")
}
func (UnimplementedSikuliServiceServer) ExistsOnScreen(context.Context, *ExistsOnScreenRequest) (*ExistsOnScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsOnScreen not implemented")
}
func (UnimplementedSikuliServiceServer) WaitOnScreen(context.Context, *WaitOnScreenRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitOnScreen not implemented")
}
func (UnimplementedSikuliServiceServer) ClickOnScreen(context.Context, *ClickOnScreenRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClickOnScreen not implemented")
}
func (UnimplementedSikuliServiceServer) ReadText(context.Context, *ReadTextRequest) (*ReadTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadText not implemented")
}
func (UnimplementedSikuliServiceServer) FindText(context.Context, *FindTextRequest) (*FindTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindText not implemented")
}
func (UnimplementedSikuliServiceServer) MoveMouse(context.Context, *MoveMouseRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveMouse not implemented")
}
func (UnimplementedSikuliServiceServer) Click(context.Context, *ClickRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedSikuliServiceServer) TypeText(context.Context, *TypeTextRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TypeText not implemented")
}
func (UnimplementedSikuliServiceServer) PasteText(context.Context, *TypeTextRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PasteText not implemented")
}
func (UnimplementedSikuliServiceServer) Hotkey(context.Context, *HotkeyRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hotkey not implemented")
}
func (UnimplementedSikuliServiceServer) MouseDown(context.Context, *ClickRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MouseDown not implemented")
}
func (UnimplementedSikuliServiceServer) MouseUp(context.Context, *ClickRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MouseUp not implemented")
}
func (UnimplementedSikuliServiceServer) KeyDown(context.Context, *HotkeyRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyDown not implemented")
}
func (UnimplementedSikuliServiceServer) KeyUp(context.Context, *HotkeyRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyUp not implemented")
}
func (UnimplementedSikuliServiceServer) ScrollWheel(context.Context, *ScrollWheelRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrollWheel not implemented")
}
func (UnimplementedSikuliServiceServer) ObserveAppear(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveAppear not implemented")
}
func (UnimplementedSikuliServiceServer) ObserveVanish(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveVanish not implemented")
}
func (UnimplementedSikuliServiceServer) ObserveChange(context.Context, *ObserveChangeRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveChange not implemented")
}
func (UnimplementedSikuliServiceServer) OpenApp(context.Context, *AppActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenApp not implemented")
}
func (UnimplementedSikuliServiceServer) FocusApp(context.Context, *AppActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FocusApp not implemented")
}
func (UnimplementedSikuliServiceServer) CloseApp(context.Context, *AppActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseApp not implemented")
}
func (UnimplementedSikuliServiceServer) IsAppRunning(context.Context, *AppActionRequest) (*IsAppRunningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAppRunning not implemented")
}
func (UnimplementedSikuliServiceServer) ListWindows(context.Context, *AppActionRequest) (*ListWindowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWindows not implemented")
}
func (UnimplementedSikuliServiceServer) FindWindows(context.Context, *WindowQueryRequest) (*ListWindowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindWindows not implemented")
}
func (UnimplementedSikuliServiceServer) GetWindow(context.Context, *WindowQueryRequest) (*GetWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWindow not implemented")
}
func (UnimplementedSikuliServiceServer) GetFocusedWindow(context.Context, *AppActionRequest) (*GetWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFocusedWindow not implemented")
}
func (UnimplementedSikuliServiceServer) mustEmbedUnimplementedSikuliServiceServer() {}
func (UnimplementedSikuliServiceServer) testEmbeddedByValue()                       {}

// UnsafeSikuliServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SikuliServiceServer will
// result in compilation errors.
type UnsafeSikuliServiceServer interface {
	mustEmbedUnimplementedSikuliServiceServer()
}

func RegisterSikuliServiceServer(s grpc.ServiceRegistrar, srv SikuliServiceServer) {
	// If the following call panics, it indicates UnimplementedSikuliServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SikuliService_ServiceDesc, srv)
}

func _SikuliService_ListScreens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScreensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ListScreens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ListScreens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ListScreens(ctx, req.(*ListScreensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_GetPrimaryScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrimaryScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).GetPrimaryScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_GetPrimaryScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).GetPrimaryScreen(ctx, req.(*GetPrimaryScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_CaptureScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).CaptureScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_CaptureScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).CaptureScreen(ctx, req.(*CaptureScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).FindAll(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_FindOnScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOnScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).FindOnScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_FindOnScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).FindOnScreen(ctx, req.(*FindOnScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ExistsOnScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsOnScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ExistsOnScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ExistsOnScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ExistsOnScreen(ctx, req.(*ExistsOnScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_WaitOnScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitOnScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).WaitOnScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_WaitOnScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).WaitOnScreen(ctx, req.(*WaitOnScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ClickOnScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickOnScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ClickOnScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ClickOnScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ClickOnScreen(ctx, req.(*ClickOnScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ReadText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ReadText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ReadText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ReadText(ctx, req.(*ReadTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_FindText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).FindText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_FindText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).FindText(ctx, req.(*FindTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_MoveMouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveMouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).MoveMouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_MoveMouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).MoveMouse(ctx, req.(*MoveMouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_TypeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).TypeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_TypeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).TypeText(ctx, req.(*TypeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_PasteText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).PasteText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_PasteText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).PasteText(ctx, req.(*TypeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_Hotkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).Hotkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_Hotkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).Hotkey(ctx, req.(*HotkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_MouseDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).MouseDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_MouseDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).MouseDown(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_MouseUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).MouseUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_MouseUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).MouseUp(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_KeyDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).KeyDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_KeyDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).KeyDown(ctx, req.(*HotkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_KeyUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).KeyUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_KeyUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).KeyUp(ctx, req.(*HotkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ScrollWheel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrollWheelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ScrollWheel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ScrollWheel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ScrollWheel(ctx, req.(*ScrollWheelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ObserveAppear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ObserveAppear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ObserveAppear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ObserveAppear(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ObserveVanish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ObserveVanish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ObserveVanish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ObserveVanish(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ObserveChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ObserveChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ObserveChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ObserveChange(ctx, req.(*ObserveChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_OpenApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).OpenApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_OpenApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).OpenApp(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_FocusApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).FocusApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_FocusApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).FocusApp(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_CloseApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).CloseApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_CloseApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).CloseApp(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_IsAppRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).IsAppRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_IsAppRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).IsAppRunning(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_ListWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).ListWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_ListWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).ListWindows(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_FindWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).FindWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_FindWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).FindWindows(ctx, req.(*WindowQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_GetWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).GetWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_GetWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).GetWindow(ctx, req.(*WindowQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SikuliService_GetFocusedWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SikuliServiceServer).GetFocusedWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SikuliService_GetFocusedWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SikuliServiceServer).GetFocusedWindow(ctx, req.(*AppActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SikuliService_ServiceDesc is the grpc.ServiceDesc for SikuliService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SikuliService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sikuli.v1.SikuliService",
	HandlerType: (*SikuliServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListScreens",
			Handler:    _SikuliService_ListScreens_Handler,
		},
		{
			MethodName: "GetPrimaryScreen",
			Handler:    _SikuliService_GetPrimaryScreen_Handler,
		},
		{
			MethodName: "CaptureScreen",
			Handler:    _SikuliService_CaptureScreen_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _SikuliService_Find_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _SikuliService_FindAll_Handler,
		},
		{
			MethodName: "FindOnScreen",
			Handler:    _SikuliService_FindOnScreen_Handler,
		},
		{
			MethodName: "ExistsOnScreen",
			Handler:    _SikuliService_ExistsOnScreen_Handler,
		},
		{
			MethodName: "WaitOnScreen",
			Handler:    _SikuliService_WaitOnScreen_Handler,
		},
		{
			MethodName: "ClickOnScreen",
			Handler:    _SikuliService_ClickOnScreen_Handler,
		},
		{
			MethodName: "ReadText",
			Handler:    _SikuliService_ReadText_Handler,
		},
		{
			MethodName: "FindText",
			Handler:    _SikuliService_FindText_Handler,
		},
		{
			MethodName: "MoveMouse",
			Handler:    _SikuliService_MoveMouse_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _SikuliService_Click_Handler,
		},
		{
			MethodName: "TypeText",
			Handler:    _SikuliService_TypeText_Handler,
		},
		{
			MethodName: "PasteText",
			Handler:    _SikuliService_PasteText_Handler,
		},
		{
			MethodName: "Hotkey",
			Handler:    _SikuliService_Hotkey_Handler,
		},
		{
			MethodName: "MouseDown",
			Handler:    _SikuliService_MouseDown_Handler,
		},
		{
			MethodName: "MouseUp",
			Handler:    _SikuliService_MouseUp_Handler,
		},
		{
			MethodName: "KeyDown",
			Handler:    _SikuliService_KeyDown_Handler,
		},
		{
			MethodName: "KeyUp",
			Handler:    _SikuliService_KeyUp_Handler,
		},
		{
			MethodName: "ScrollWheel",
			Handler:    _SikuliService_ScrollWheel_Handler,
		},
		{
			MethodName: "ObserveAppear",
			Handler:    _SikuliService_ObserveAppear_Handler,
		},
		{
			MethodName: "ObserveVanish",
			Handler:    _SikuliService_ObserveVanish_Handler,
		},
		{
			MethodName: "ObserveChange",
			Handler:    _SikuliService_ObserveChange_Handler,
		},
		{
			MethodName: "OpenApp",
			Handler:    _SikuliService_OpenApp_Handler,
		},
		{
			MethodName: "FocusApp",
			Handler:    _SikuliService_FocusApp_Handler,
		},
		{
			MethodName: "CloseApp",
			Handler:    _SikuliService_CloseApp_Handler,
		},
		{
			MethodName: "IsAppRunning",
			Handler:    _SikuliService_IsAppRunning_Handler,
		},
		{
			MethodName: "ListWindows",
			Handler:    _SikuliService_ListWindows_Handler,
		},
		{
			MethodName: "FindWindows",
			Handler:    _SikuliService_FindWindows_Handler,
		},
		{
			MethodName: "GetWindow",
			Handler:    _SikuliService_GetWindow_Handler,
		},
		{
			MethodName: "GetFocusedWindow",
			Handler:    _SikuliService_GetFocusedWindow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sikuli/v1/sikuli.proto",
}
