// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: sikuli/v1/sikuli.proto

package sikuliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatcherEngine int32

const (
	MatcherEngine_MATCHER_ENGINE_UNSPECIFIED MatcherEngine = 0
	MatcherEngine_MATCHER_ENGINE_TEMPLATE    MatcherEngine = 1
	MatcherEngine_MATCHER_ENGINE_ORB         MatcherEngine = 2
	MatcherEngine_MATCHER_ENGINE_HYBRID      MatcherEngine = 3
	MatcherEngine_MATCHER_ENGINE_AKAZE       MatcherEngine = 4
	MatcherEngine_MATCHER_ENGINE_BRISK       MatcherEngine = 5
	MatcherEngine_MATCHER_ENGINE_KAZE        MatcherEngine = 6
	MatcherEngine_MATCHER_ENGINE_SIFT        MatcherEngine = 7
)

// Enum value maps for MatcherEngine.
var (
	MatcherEngine_name = map[int32]string{
		0: "MATCHER_ENGINE_UNSPECIFIED",
		1: "MATCHER_ENGINE_TEMPLATE",
		2: "MATCHER_ENGINE_ORB",
		3: "MATCHER_ENGINE_HYBRID",
		4: "MATCHER_ENGINE_AKAZE",
		5: "MATCHER_ENGINE_BRISK",
		6: "MATCHER_ENGINE_KAZE",
		7: "MATCHER_ENGINE_SIFT",
	}
	MatcherEngine_value = map[string]int32{
		"MATCHER_ENGINE_UNSPECIFIED": 0,
		"MATCHER_ENGINE_TEMPLATE":    1,
		"MATCHER_ENGINE_ORB":         2,
		"MATCHER_ENGINE_HYBRID":      3,
		"MATCHER_ENGINE_AKAZE":       4,
		"MATCHER_ENGINE_BRISK":       5,
		"MATCHER_ENGINE_KAZE":        6,
		"MATCHER_ENGINE_SIFT":        7,
	}
)

func (x MatcherEngine) Enum() *MatcherEngine {
	p := new(MatcherEngine)
	*p = x
	return p
}

func (x MatcherEngine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatcherEngine) Descriptor() protoreflect.EnumDescriptor {
	return file_sikuli_v1_sikuli_proto_enumTypes[0].Descriptor()
}

func (MatcherEngine) Type() protoreflect.EnumType {
	return &file_sikuli_v1_sikuli_proto_enumTypes[0]
}

func (x MatcherEngine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatcherEngine.Descriptor instead.
func (MatcherEngine) EnumDescriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{0}
}

type GrayImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Pix           []byte                 `protobuf:"bytes,4,opt,name=pix,proto3" json:"pix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrayImage) Reset() {
	*x = GrayImage{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrayImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayImage) ProtoMessage() {}

func (x *GrayImage) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayImage.ProtoReflect.Descriptor instead.
func (*GrayImage) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{0}
}

func (x *GrayImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrayImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GrayImage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GrayImage) GetPix() []byte {
	if x != nil {
		return x.Pix
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{2}
}

func (x *Rect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Rect) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *GrayImage             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Similarity    *float64               `protobuf:"fixed64,2,opt,name=similarity,proto3,oneof" json:"similarity,omitempty"`
	Exact         *bool                  `protobuf:"varint,3,opt,name=exact,proto3,oneof" json:"exact,omitempty"`
	TargetOffset  *Point                 `protobuf:"bytes,4,opt,name=target_offset,json=targetOffset,proto3" json:"target_offset,omitempty"`
	ResizeFactor  *float64               `protobuf:"fixed64,5,opt,name=resize_factor,json=resizeFactor,proto3,oneof" json:"resize_factor,omitempty"`
	Mask          *GrayImage             `protobuf:"bytes,6,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{3}
}

func (x *Pattern) GetImage() *GrayImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Pattern) GetSimilarity() float64 {
	if x != nil && x.Similarity != nil {
		return *x.Similarity
	}
	return 0
}

func (x *Pattern) GetExact() bool {
	if x != nil && x.Exact != nil {
		return *x.Exact
	}
	return false
}

func (x *Pattern) GetTargetOffset() *Point {
	if x != nil {
		return x.TargetOffset
	}
	return nil
}

func (x *Pattern) GetResizeFactor() float64 {
	if x != nil && x.ResizeFactor != nil {
		return *x.ResizeFactor
	}
	return 0
}

func (x *Pattern) GetMask() *GrayImage {
	if x != nil {
		return x.Mask
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rect          *Rect                  `protobuf:"bytes,1,opt,name=rect,proto3" json:"rect,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Target        *Point                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{4}
}

func (x *Match) GetRect() *Rect {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *Match) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Match) GetTarget() *Point {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Match) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type TextMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rect          *Rect                  `protobuf:"bytes,1,opt,name=rect,proto3" json:"rect,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMatch) Reset() {
	*x = TextMatch{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMatch) ProtoMessage() {}

func (x *TextMatch) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMatch.ProtoReflect.Descriptor instead.
func (*TextMatch) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{5}
}

func (x *TextMatch) GetRect() *Rect {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *TextMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextMatch) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TextMatch) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type OCRParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Language         string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	TrainingDataPath string                 `protobuf:"bytes,2,opt,name=training_data_path,json=trainingDataPath,proto3" json:"training_data_path,omitempty"`
	MinConfidence    *float64               `protobuf:"fixed64,3,opt,name=min_confidence,json=minConfidence,proto3,oneof" json:"min_confidence,omitempty"`
	TimeoutMillis    *int64                 `protobuf:"varint,4,opt,name=timeout_millis,json=timeoutMillis,proto3,oneof" json:"timeout_millis,omitempty"`
	CaseSensitive    *bool                  `protobuf:"varint,5,opt,name=case_sensitive,json=caseSensitive,proto3,oneof" json:"case_sensitive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OCRParams) Reset() {
	*x = OCRParams{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRParams) ProtoMessage() {}

func (x *OCRParams) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRParams.ProtoReflect.Descriptor instead.
func (*OCRParams) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{6}
}

func (x *OCRParams) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *OCRParams) GetTrainingDataPath() string {
	if x != nil {
		return x.TrainingDataPath
	}
	return ""
}

func (x *OCRParams) GetMinConfidence() float64 {
	if x != nil && x.MinConfidence != nil {
		return *x.MinConfidence
	}
	return 0
}

func (x *OCRParams) GetTimeoutMillis() int64 {
	if x != nil && x.TimeoutMillis != nil {
		return *x.TimeoutMillis
	}
	return 0
}

func (x *OCRParams) GetCaseSensitive() bool {
	if x != nil && x.CaseSensitive != nil {
		return *x.CaseSensitive
	}
	return false
}

type InputOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMillis   *int64                 `protobuf:"varint,1,opt,name=delay_millis,json=delayMillis,proto3,oneof" json:"delay_millis,omitempty"`
	Button        string                 `protobuf:"bytes,2,opt,name=button,proto3" json:"button,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputOptions) Reset() {
	*x = InputOptions{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputOptions) ProtoMessage() {}

func (x *InputOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputOptions.ProtoReflect.Descriptor instead.
func (*InputOptions) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{7}
}

func (x *InputOptions) GetDelayMillis() int64 {
	if x != nil && x.DelayMillis != nil {
		return *x.DelayMillis
	}
	return 0
}

func (x *InputOptions) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

type ObserveOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntervalMillis *int64                 `protobuf:"varint,1,opt,name=interval_millis,json=intervalMillis,proto3,oneof" json:"interval_millis,omitempty"`
	TimeoutMillis  *int64                 `protobuf:"varint,2,opt,name=timeout_millis,json=timeoutMillis,proto3,oneof" json:"timeout_millis,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObserveOptions) Reset() {
	*x = ObserveOptions{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveOptions) ProtoMessage() {}

func (x *ObserveOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveOptions.ProtoReflect.Descriptor instead.
func (*ObserveOptions) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{8}
}

func (x *ObserveOptions) GetIntervalMillis() int64 {
	if x != nil && x.IntervalMillis != nil {
		return *x.IntervalMillis
	}
	return 0
}

func (x *ObserveOptions) GetTimeoutMillis() int64 {
	if x != nil && x.TimeoutMillis != nil {
		return *x.TimeoutMillis
	}
	return 0
}

type AppOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMillis *int64                 `protobuf:"varint,1,opt,name=timeout_millis,json=timeoutMillis,proto3,oneof" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppOptions) Reset() {
	*x = AppOptions{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOptions) ProtoMessage() {}

func (x *AppOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOptions.ProtoReflect.Descriptor instead.
func (*AppOptions) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{9}
}

func (x *AppOptions) GetTimeoutMillis() int64 {
	if x != nil && x.TimeoutMillis != nil {
		return *x.TimeoutMillis
	}
	return 0
}

type Window struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Bounds        *Rect                  `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Focused       bool                   `protobuf:"varint,3,opt,name=focused,proto3" json:"focused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{10}
}

func (x *Window) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Window) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Window) GetFocused() bool {
	if x != nil {
		return x.Focused
	}
	return false
}

type ObserveEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Match               *Match                 `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	TimestampUnixMillis int64                  `protobuf:"varint,3,opt,name=timestamp_unix_millis,json=timestampUnixMillis,proto3" json:"timestamp_unix_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObserveEvent) Reset() {
	*x = ObserveEvent{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveEvent) ProtoMessage() {}

func (x *ObserveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveEvent.ProtoReflect.Descriptor instead.
func (*ObserveEvent) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{11}
}

func (x *ObserveEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObserveEvent) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *ObserveEvent) GetTimestampUnixMillis() int64 {
	if x != nil {
		return x.TimestampUnixMillis
	}
	return 0
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *GrayImage             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Pattern       *Pattern               `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	MatcherEngine MatcherEngine          `protobuf:"varint,3,opt,name=matcher_engine,json=matcherEngine,proto3,enum=sikuli.v1.MatcherEngine" json:"matcher_engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{12}
}

func (x *FindRequest) GetSource() *GrayImage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FindRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *FindRequest) GetMatcherEngine() MatcherEngine {
	if x != nil {
		return x.MatcherEngine
	}
	return MatcherEngine_MATCHER_ENGINE_UNSPECIFIED
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{13}
}

func (x *FindResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{14}
}

func (x *FindAllResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ScreenQueryOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         *Rect                  `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	TimeoutMillis  *int64                 `protobuf:"varint,2,opt,name=timeout_millis,json=timeoutMillis,proto3,oneof" json:"timeout_millis,omitempty"`
	IntervalMillis *int64                 `protobuf:"varint,3,opt,name=interval_millis,json=intervalMillis,proto3,oneof" json:"interval_millis,omitempty"`
	MatcherEngine  MatcherEngine          `protobuf:"varint,4,opt,name=matcher_engine,json=matcherEngine,proto3,enum=sikuli.v1.MatcherEngine" json:"matcher_engine,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScreenQueryOptions) Reset() {
	*x = ScreenQueryOptions{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenQueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenQueryOptions) ProtoMessage() {}

func (x *ScreenQueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenQueryOptions.ProtoReflect.Descriptor instead.
func (*ScreenQueryOptions) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{15}
}

func (x *ScreenQueryOptions) GetRegion() *Rect {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ScreenQueryOptions) GetTimeoutMillis() int64 {
	if x != nil && x.TimeoutMillis != nil {
		return *x.TimeoutMillis
	}
	return 0
}

func (x *ScreenQueryOptions) GetIntervalMillis() int64 {
	if x != nil && x.IntervalMillis != nil {
		return *x.IntervalMillis
	}
	return 0
}

func (x *ScreenQueryOptions) GetMatcherEngine() MatcherEngine {
	if x != nil {
		return x.MatcherEngine
	}
	return MatcherEngine_MATCHER_ENGINE_UNSPECIFIED
}

type FindOnScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *Pattern               `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Opts          *ScreenQueryOptions    `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOnScreenRequest) Reset() {
	*x = FindOnScreenRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOnScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOnScreenRequest) ProtoMessage() {}

func (x *FindOnScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOnScreenRequest.ProtoReflect.Descriptor instead.
func (*FindOnScreenRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{16}
}

func (x *FindOnScreenRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *FindOnScreenRequest) GetOpts() *ScreenQueryOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ExistsOnScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *Pattern               `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Opts          *ScreenQueryOptions    `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsOnScreenRequest) Reset() {
	*x = ExistsOnScreenRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsOnScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsOnScreenRequest) ProtoMessage() {}

func (x *ExistsOnScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsOnScreenRequest.ProtoReflect.Descriptor instead.
func (*ExistsOnScreenRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{17}
}

func (x *ExistsOnScreenRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *ExistsOnScreenRequest) GetOpts() *ScreenQueryOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ExistsOnScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Match         *Match                 `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsOnScreenResponse) Reset() {
	*x = ExistsOnScreenResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsOnScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsOnScreenResponse) ProtoMessage() {}

func (x *ExistsOnScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsOnScreenResponse.ProtoReflect.Descriptor instead.
func (*ExistsOnScreenResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{18}
}

func (x *ExistsOnScreenResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExistsOnScreenResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type WaitOnScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *Pattern               `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Opts          *ScreenQueryOptions    `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitOnScreenRequest) Reset() {
	*x = WaitOnScreenRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitOnScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitOnScreenRequest) ProtoMessage() {}

func (x *WaitOnScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitOnScreenRequest.ProtoReflect.Descriptor instead.
func (*WaitOnScreenRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{19}
}

func (x *WaitOnScreenRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *WaitOnScreenRequest) GetOpts() *ScreenQueryOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ClickOnScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *Pattern               `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Opts          *ScreenQueryOptions    `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	ClickOpts     *InputOptions          `protobuf:"bytes,3,opt,name=click_opts,json=clickOpts,proto3" json:"click_opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickOnScreenRequest) Reset() {
	*x = ClickOnScreenRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickOnScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickOnScreenRequest) ProtoMessage() {}

func (x *ClickOnScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickOnScreenRequest.ProtoReflect.Descriptor instead.
func (*ClickOnScreenRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{20}
}

func (x *ClickOnScreenRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *ClickOnScreenRequest) GetOpts() *ScreenQueryOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *ClickOnScreenRequest) GetClickOpts() *InputOptions {
	if x != nil {
		return x.ClickOpts
	}
	return nil
}

type ReadTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *GrayImage             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Params        *OCRParams             `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTextRequest) Reset() {
	*x = ReadTextRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTextRequest) ProtoMessage() {}

func (x *ReadTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTextRequest.ProtoReflect.Descriptor instead.
func (*ReadTextRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{21}
}

func (x *ReadTextRequest) GetSource() *GrayImage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ReadTextRequest) GetParams() *OCRParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ReadTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTextResponse) Reset() {
	*x = ReadTextResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTextResponse) ProtoMessage() {}

func (x *ReadTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTextResponse.ProtoReflect.Descriptor instead.
func (*ReadTextResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{22}
}

func (x *ReadTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FindTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *GrayImage             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Params        *OCRParams             `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTextRequest) Reset() {
	*x = FindTextRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTextRequest) ProtoMessage() {}

func (x *FindTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTextRequest.ProtoReflect.Descriptor instead.
func (*FindTextRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{23}
}

func (x *FindTextRequest) GetSource() *GrayImage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FindTextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FindTextRequest) GetParams() *OCRParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type FindTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*TextMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTextResponse) Reset() {
	*x = FindTextResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTextResponse) ProtoMessage() {}

func (x *FindTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTextResponse.ProtoReflect.Descriptor instead.
func (*FindTextResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{24}
}

func (x *FindTextResponse) GetMatches() []*TextMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type MoveMouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Opts          *InputOptions          `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveMouseRequest) Reset() {
	*x = MoveMouseRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMouseRequest) ProtoMessage() {}

func (x *MoveMouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMouseRequest.ProtoReflect.Descriptor instead.
func (*MoveMouseRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{25}
}

func (x *MoveMouseRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveMouseRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveMouseRequest) GetOpts() *InputOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Opts          *InputOptions          `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{26}
}

func (x *ClickRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickRequest) GetOpts() *InputOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type TypeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Opts          *InputOptions          `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTextRequest) Reset() {
	*x = TypeTextRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTextRequest) ProtoMessage() {}

func (x *TypeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTextRequest.ProtoReflect.Descriptor instead.
func (*TypeTextRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{27}
}

func (x *TypeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TypeTextRequest) GetOpts() *InputOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type HotkeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotkeyRequest) Reset() {
	*x = HotkeyRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotkeyRequest) ProtoMessage() {}

func (x *HotkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotkeyRequest.ProtoReflect.Descriptor instead.
func (*HotkeyRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{28}
}

func (x *HotkeyRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{29}
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *GrayImage             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Region        *Rect                  `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Pattern       *Pattern               `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Opts          *ObserveOptions        `protobuf:"bytes,4,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{30}
}

func (x *ObserveRequest) GetSource() *GrayImage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ObserveRequest) GetRegion() *Rect {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ObserveRequest) GetPattern() *Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *ObserveRequest) GetOpts() *ObserveOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ObserveChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *GrayImage             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Region        *Rect                  `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Opts          *ObserveOptions        `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveChangeRequest) Reset() {
	*x = ObserveChangeRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveChangeRequest) ProtoMessage() {}

func (x *ObserveChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveChangeRequest.ProtoReflect.Descriptor instead.
func (*ObserveChangeRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{31}
}

func (x *ObserveChangeRequest) GetSource() *GrayImage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ObserveChangeRequest) GetRegion() *Rect {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ObserveChangeRequest) GetOpts() *ObserveOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ObserveEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{32}
}

func (x *ObserveResponse) GetEvents() []*ObserveEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AppActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Opts          *AppOptions            `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppActionRequest) Reset() {
	*x = AppActionRequest{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppActionRequest) ProtoMessage() {}

func (x *AppActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppActionRequest.ProtoReflect.Descriptor instead.
func (*AppActionRequest) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{33}
}

func (x *AppActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppActionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AppActionRequest) GetOpts() *AppOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type IsAppRunningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAppRunningResponse) Reset() {
	*x = IsAppRunningResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAppRunningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAppRunningResponse) ProtoMessage() {}

func (x *IsAppRunningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAppRunningResponse.ProtoReflect.Descriptor instead.
func (*IsAppRunningResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{34}
}

func (x *IsAppRunningResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type ListWindowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Windows       []*Window              `protobuf:"bytes,1,rep,name=windows,proto3" json:"windows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWindowsResponse) Reset() {
	*x = ListWindowsResponse{}
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWindowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWindowsResponse) ProtoMessage() {}

func (x *ListWindowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sikuli_v1_sikuli_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWindowsResponse.ProtoReflect.Descriptor instead.
func (*ListWindowsResponse) Descriptor() ([]byte, []int) {
	return file_sikuli_v1_sikuli_proto_rawDescGZIP(), []int{35}
}

func (x *ListWindowsResponse) GetWindows() []*Window {
	if x != nil {
		return x.Windows
	}
	return nil
}

var File_sikuli_v1_sikuli_proto protoreflect.FileDescriptor

const file_sikuli_v1_sikuli_proto_rawDesc = "" +
	"\n" +
	"\x16sikuli/v1/sikuli.proto\x12\tsikuli.v1\"_\n" +
	"\tGrayImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x10\n" +
	"\x03pix\x18\x04 \x01(\fR\x03pix\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\">\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\"\xab\x02\n" +
	"\aPattern\x12*\n" +
	"\x05image\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x05image\x12#\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x01H\x00R\n" +
	"similarity\x88\x01\x01\x12\x19\n" +
	"\x05exact\x18\x03 \x01(\bH\x01R\x05exact\x88\x01\x01\x125\n" +
	"\rtarget_offset\x18\x04 \x01(\v2\x10.sikuli.v1.PointR\ftargetOffset\x12(\n" +
	"\rresize_factor\x18\x05 \x01(\x01H\x02R\fresizeFactor\x88\x01\x01\x12(\n" +
	"\x04mask\x18\x06 \x01(\v2\x14.sikuli.v1.GrayImageR\x04maskB\r\n" +
	"\v_similarityB\b\n" +
	"\x06_exactB\x10\n" +
	"\x0e_resize_factor\"\x82\x01\n" +
	"\x05Match\x12#\n" +
	"\x04rect\x18\x01 \x01(\v2\x0f.sikuli.v1.RectR\x04rect\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12(\n" +
	"\x06target\x18\x03 \x01(\v2\x10.sikuli.v1.PointR\x06target\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\"z\n" +
	"\tTextMatch\x12#\n" +
	"\x04rect\x18\x01 \x01(\v2\x0f.sikuli.v1.RectR\x04rect\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\"\x92\x02\n" +
	"\tOCRParams\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12,\n" +
	"\x12training_data_path\x18\x02 \x01(\tR\x10trainingDataPath\x12*\n" +
	"\x0emin_confidence\x18\x03 \x01(\x01H\x00R\rminConfidence\x88\x01\x01\x12*\n" +
	"\x0etimeout_millis\x18\x04 \x01(\x03H\x01R\rtimeoutMillis\x88\x01\x01\x12*\n" +
	"\x0ecase_sensitive\x18\x05 \x01(\bH\x02R\rcaseSensitive\x88\x01\x01B\x11\n" +
	"\x0f_min_confidenceB\x11\n" +
	"\x0f_timeout_millisB\x11\n" +
	"\x0f_case_sensitive\"_\n" +
	"\fInputOptions\x12&\n" +
	"\fdelay_millis\x18\x01 \x01(\x03H\x00R\vdelayMillis\x88\x01\x01\x12\x16\n" +
	"\x06button\x18\x02 \x01(\tR\x06buttonB\x0f\n" +
	"\r_delay_millis\"\x91\x01\n" +
	"\x0eObserveOptions\x12,\n" +
	"\x0finterval_millis\x18\x01 \x01(\x03H\x00R\x0eintervalMillis\x88\x01\x01\x12*\n" +
	"\x0etimeout_millis\x18\x02 \x01(\x03H\x01R\rtimeoutMillis\x88\x01\x01B\x12\n" +
	"\x10_interval_millisB\x11\n" +
	"\x0f_timeout_millis\"K\n" +
	"\n" +
	"AppOptions\x12*\n" +
	"\x0etimeout_millis\x18\x01 \x01(\x03H\x00R\rtimeoutMillis\x88\x01\x01B\x11\n" +
	"\x0f_timeout_millis\"a\n" +
	"\x06Window\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12'\n" +
	"\x06bounds\x18\x02 \x01(\v2\x0f.sikuli.v1.RectR\x06bounds\x12\x18\n" +
	"\afocused\x18\x03 \x01(\bR\afocused\"~\n" +
	"\fObserveEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12&\n" +
	"\x05match\x18\x02 \x01(\v2\x10.sikuli.v1.MatchR\x05match\x122\n" +
	"\x15timestamp_unix_millis\x18\x03 \x01(\x03R\x13timestampUnixMillis\"\xaa\x01\n" +
	"\vFindRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x06source\x12,\n" +
	"\apattern\x18\x02 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x12?\n" +
	"\x0ematcher_engine\x18\x03 \x01(\x0e2\x18.sikuli.v1.MatcherEngineR\rmatcherEngine\"6\n" +
	"\fFindResponse\x12&\n" +
	"\x05match\x18\x01 \x01(\v2\x10.sikuli.v1.MatchR\x05match\"=\n" +
	"\x0fFindAllResponse\x12*\n" +
	"\amatches\x18\x01 \x03(\v2\x10.sikuli.v1.MatchR\amatches\"\xff\x01\n" +
	"\x12ScreenQueryOptions\x12'\n" +
	"\x06region\x18\x01 \x01(\v2\x0f.sikuli.v1.RectR\x06region\x12*\n" +
	"\x0etimeout_millis\x18\x02 \x01(\x03H\x00R\rtimeoutMillis\x88\x01\x01\x12,\n" +
	"\x0finterval_millis\x18\x03 \x01(\x03H\x01R\x0eintervalMillis\x88\x01\x01\x12?\n" +
	"\x0ematcher_engine\x18\x04 \x01(\x0e2\x18.sikuli.v1.MatcherEngineR\rmatcherEngineB\x11\n" +
	"\x0f_timeout_millisB\x12\n" +
	"\x10_interval_millis\"v\n" +
	"\x13FindOnScreenRequest\x12,\n" +
	"\apattern\x18\x01 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x121\n" +
	"\x04opts\x18\x02 \x01(\v2\x1d.sikuli.v1.ScreenQueryOptionsR\x04opts\"x\n" +
	"\x15ExistsOnScreenRequest\x12,\n" +
	"\apattern\x18\x01 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x121\n" +
	"\x04opts\x18\x02 \x01(\v2\x1d.sikuli.v1.ScreenQueryOptionsR\x04opts\"X\n" +
	"\x16ExistsOnScreenResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12&\n" +
	"\x05match\x18\x02 \x01(\v2\x10.sikuli.v1.MatchR\x05match\"v\n" +
	"\x13WaitOnScreenRequest\x12,\n" +
	"\apattern\x18\x01 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x121\n" +
	"\x04opts\x18\x02 \x01(\v2\x1d.sikuli.v1.ScreenQueryOptionsR\x04opts\"\xaf\x01\n" +
	"\x14ClickOnScreenRequest\x12,\n" +
	"\apattern\x18\x01 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x121\n" +
	"\x04opts\x18\x02 \x01(\v2\x1d.sikuli.v1.ScreenQueryOptionsR\x04opts\x126\n" +
	"\n" +
	"click_opts\x18\x03 \x01(\v2\x17.sikuli.v1.InputOptionsR\tclickOpts\"m\n" +
	"\x0fReadTextRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x06source\x12,\n" +
	"\x06params\x18\x02 \x01(\v2\x14.sikuli.v1.OCRParamsR\x06params\"&\n" +
	"\x10ReadTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x83\x01\n" +
	"\x0fFindTextRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x06source\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12,\n" +
	"\x06params\x18\x03 \x01(\v2\x14.sikuli.v1.OCRParamsR\x06params\"B\n" +
	"\x10FindTextResponse\x12.\n" +
	"\amatches\x18\x01 \x03(\v2\x14.sikuli.v1.TextMatchR\amatches\"[\n" +
	"\x10MoveMouseRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12+\n" +
	"\x04opts\x18\x03 \x01(\v2\x17.sikuli.v1.InputOptionsR\x04opts\"W\n" +
	"\fClickRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12+\n" +
	"\x04opts\x18\x03 \x01(\v2\x17.sikuli.v1.InputOptionsR\x04opts\"R\n" +
	"\x0fTypeTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12+\n" +
	"\x04opts\x18\x02 \x01(\v2\x17.sikuli.v1.InputOptionsR\x04opts\"#\n" +
	"\rHotkeyRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x10\n" +
	"\x0eActionResponse\"\xc4\x01\n" +
	"\x0eObserveRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x06source\x12'\n" +
	"\x06region\x18\x02 \x01(\v2\x0f.sikuli.v1.RectR\x06region\x12,\n" +
	"\apattern\x18\x03 \x01(\v2\x12.sikuli.v1.PatternR\apattern\x12-\n" +
	"\x04opts\x18\x04 \x01(\v2\x19.sikuli.v1.ObserveOptionsR\x04opts\"\x9c\x01\n" +
	"\x14ObserveChangeRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.sikuli.v1.GrayImageR\x06source\x12'\n" +
	"\x06region\x18\x02 \x01(\v2\x0f.sikuli.v1.RectR\x06region\x12-\n" +
	"\x04opts\x18\x03 \x01(\v2\x19.sikuli.v1.ObserveOptionsR\x04opts\"B\n" +
	"\x0fObserveResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.sikuli.v1.ObserveEventR\x06events\"e\n" +
	"\x10AppActionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12)\n" +
	"\x04opts\x18\x03 \x01(\v2\x15.sikuli.v1.AppOptionsR\x04opts\"0\n" +
	"\x14IsAppRunningResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\"B\n" +
	"\x13ListWindowsResponse\x12+\n" +
	"\awindows\x18\x01 \x03(\v2\x11.sikuli.v1.WindowR\awindows*\xe5\x01\n" +
	"\rMatcherEngine\x12\x1e\n" +
	"\x1aMATCHER_ENGINE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MATCHER_ENGINE_TEMPLATE\x10\x01\x12\x16\n" +
	"\x12MATCHER_ENGINE_ORB\x10\x02\x12\x19\n" +
	"\x15MATCHER_ENGINE_HYBRID\x10\x03\x12\x18\n" +
	"\x14MATCHER_ENGINE_AKAZE\x10\x04\x12\x18\n" +
	"\x14MATCHER_ENGINE_BRISK\x10\x05\x12\x17\n" +
	"\x13MATCHER_ENGINE_KAZE\x10\x06\x12\x17\n" +
	"\x13MATCHER_ENGINE_SIFT\x10\a2\x8c\v\n" +
	"\rSikuliService\x127\n" +
	"\x04Find\x12\x16.sikuli.v1.FindRequest\x1a\x17.sikuli.v1.FindResponse\x12=\n" +
	"\aFindAll\x12\x16.sikuli.v1.FindRequest\x1a\x1a.sikuli.v1.FindAllResponse\x12G\n" +
	"\fFindOnScreen\x12\x1e.sikuli.v1.FindOnScreenRequest\x1a\x17.sikuli.v1.FindResponse\x12U\n" +
	"\x0eExistsOnScreen\x12 .sikuli.v1.ExistsOnScreenRequest\x1a!.sikuli.v1.ExistsOnScreenResponse\x12G\n" +
	"\fWaitOnScreen\x12\x1e.sikuli.v1.WaitOnScreenRequest\x1a\x17.sikuli.v1.FindResponse\x12I\n" +
	"\rClickOnScreen\x12\x1f.sikuli.v1.ClickOnScreenRequest\x1a\x17.sikuli.v1.FindResponse\x12C\n" +
	"\bReadText\x12\x1a.sikuli.v1.ReadTextRequest\x1a\x1b.sikuli.v1.ReadTextResponse\x12C\n" +
	"\bFindText\x12\x1a.sikuli.v1.FindTextRequest\x1a\x1b.sikuli.v1.FindTextResponse\x12C\n" +
	"\tMoveMouse\x12\x1b.sikuli.v1.MoveMouseRequest\x1a\x19.sikuli.v1.ActionResponse\x12;\n" +
	"\x05Click\x12\x17.sikuli.v1.ClickRequest\x1a\x19.sikuli.v1.ActionResponse\x12A\n" +
	"\bTypeText\x12\x1a.sikuli.v1.TypeTextRequest\x1a\x19.sikuli.v1.ActionResponse\x12=\n" +
	"\x06Hotkey\x12\x18.sikuli.v1.HotkeyRequest\x1a\x19.sikuli.v1.ActionResponse\x12F\n" +
	"\rObserveAppear\x12\x19.sikuli.v1.ObserveRequest\x1a\x1a.sikuli.v1.ObserveResponse\x12F\n" +
	"\rObserveVanish\x12\x19.sikuli.v1.ObserveRequest\x1a\x1a.sikuli.v1.ObserveResponse\x12L\n" +
	"\rObserveChange\x12\x1f.sikuli.v1.ObserveChangeRequest\x1a\x1a.sikuli.v1.ObserveResponse\x12A\n" +
	"\aOpenApp\x12\x1b.sikuli.v1.AppActionRequest\x1a\x19.sikuli.v1.ActionResponse\x12B\n" +
	"\bFocusApp\x12\x1b.sikuli.v1.AppActionRequest\x1a\x19.sikuli.v1.ActionResponse\x12B\n" +
	"\bCloseApp\x12\x1b.sikuli.v1.AppActionRequest\x1a\x19.sikuli.v1.ActionResponse\x12L\n" +
	"\fIsAppRunning\x12\x1b.sikuli.v1.AppActionRequest\x1a\x1f.sikuli.v1.IsAppRunningResponse\x12J\n" +
	"\vListWindows\x12\x1b.sikuli.v1.AppActionRequest\x1a\x1e.sikuli.v1.ListWindowsResponseB8Z6github.com/smysnk/sikuligo/internal/grpcv1/pb;sikuliv1b\x06proto3"

var (
	file_sikuli_v1_sikuli_proto_rawDescOnce sync.Once
	file_sikuli_v1_sikuli_proto_rawDescData []byte
)

func file_sikuli_v1_sikuli_proto_rawDescGZIP() []byte {
	file_sikuli_v1_sikuli_proto_rawDescOnce.Do(func() {
		file_sikuli_v1_sikuli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sikuli_v1_sikuli_proto_rawDesc), len(file_sikuli_v1_sikuli_proto_rawDesc)))
	})
	return file_sikuli_v1_sikuli_proto_rawDescData
}

var file_sikuli_v1_sikuli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sikuli_v1_sikuli_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_sikuli_v1_sikuli_proto_goTypes = []any{
	(MatcherEngine)(0),             // 0: sikuli.v1.MatcherEngine
	(*GrayImage)(nil),              // 1: sikuli.v1.GrayImage
	(*Point)(nil),                  // 2: sikuli.v1.Point
	(*Rect)(nil),                   // 3: sikuli.v1.Rect
	(*Pattern)(nil),                // 4: sikuli.v1.Pattern
	(*Match)(nil),                  // 5: sikuli.v1.Match
	(*TextMatch)(nil),              // 6: sikuli.v1.TextMatch
	(*OCRParams)(nil),              // 7: sikuli.v1.OCRParams
	(*InputOptions)(nil),           // 8: sikuli.v1.InputOptions
	(*ObserveOptions)(nil),         // 9: sikuli.v1.ObserveOptions
	(*AppOptions)(nil),             // 10: sikuli.v1.AppOptions
	(*Window)(nil),                 // 11: sikuli.v1.Window
	(*ObserveEvent)(nil),           // 12: sikuli.v1.ObserveEvent
	(*FindRequest)(nil),            // 13: sikuli.v1.FindRequest
	(*FindResponse)(nil),           // 14: sikuli.v1.FindResponse
	(*FindAllResponse)(nil),        // 15: sikuli.v1.FindAllResponse
	(*ScreenQueryOptions)(nil),     // 16: sikuli.v1.ScreenQueryOptions
	(*FindOnScreenRequest)(nil),    // 17: sikuli.v1.FindOnScreenRequest
	(*ExistsOnScreenRequest)(nil),  // 18: sikuli.v1.ExistsOnScreenRequest
	(*ExistsOnScreenResponse)(nil), // 19: sikuli.v1.ExistsOnScreenResponse
	(*WaitOnScreenRequest)(nil),    // 20: sikuli.v1.WaitOnScreenRequest
	(*ClickOnScreenRequest)(nil),   // 21: sikuli.v1.ClickOnScreenRequest
	(*ReadTextRequest)(nil),        // 22: sikuli.v1.ReadTextRequest
	(*ReadTextResponse)(nil),       // 23: sikuli.v1.ReadTextResponse
	(*FindTextRequest)(nil),        // 24: sikuli.v1.FindTextRequest
	(*FindTextResponse)(nil),       // 25: sikuli.v1.FindTextResponse
	(*MoveMouseRequest)(nil),       // 26: sikuli.v1.MoveMouseRequest
	(*ClickRequest)(nil),           // 27: sikuli.v1.ClickRequest
	(*TypeTextRequest)(nil),        // 28: sikuli.v1.TypeTextRequest
	(*HotkeyRequest)(nil),          // 29: sikuli.v1.HotkeyRequest
	(*ActionResponse)(nil),         // 30: sikuli.v1.ActionResponse
	(*ObserveRequest)(nil),         // 31: sikuli.v1.ObserveRequest
	(*ObserveChangeRequest)(nil),   // 32: sikuli.v1.ObserveChangeRequest
	(*ObserveResponse)(nil),        // 33: sikuli.v1.ObserveResponse
	(*AppActionRequest)(nil),       // 34: sikuli.v1.AppActionRequest
	(*IsAppRunningResponse)(nil),   // 35: sikuli.v1.IsAppRunningResponse
	(*ListWindowsResponse)(nil),    // 36: sikuli.v1.ListWindowsResponse
}
var file_sikuli_v1_sikuli_proto_depIdxs = []int32{
	1,  // 0: sikuli.v1.Pattern.image:type_name -> sikuli.v1.GrayImage
	2,  // 1: sikuli.v1.Pattern.target_offset:type_name -> sikuli.v1.Point
	1,  // 2: sikuli.v1.Pattern.mask:type_name -> sikuli.v1.GrayImage
	3,  // 3: sikuli.v1.Match.rect:type_name -> sikuli.v1.Rect
	2,  // 4: sikuli.v1.Match.target:type_name -> sikuli.v1.Point
	3,  // 5: sikuli.v1.TextMatch.rect:type_name -> sikuli.v1.Rect
	3,  // 6: sikuli.v1.Window.bounds:type_name -> sikuli.v1.Rect
	5,  // 7: sikuli.v1.ObserveEvent.match:type_name -> sikuli.v1.Match
	1,  // 8: sikuli.v1.FindRequest.source:type_name -> sikuli.v1.GrayImage
	4,  // 9: sikuli.v1.FindRequest.pattern:type_name -> sikuli.v1.Pattern
	0,  // 10: sikuli.v1.FindRequest.matcher_engine:type_name -> sikuli.v1.MatcherEngine
	5,  // 11: sikuli.v1.FindResponse.match:type_name -> sikuli.v1.Match
	5,  // 12: sikuli.v1.FindAllResponse.matches:type_name -> sikuli.v1.Match
	3,  // 13: sikuli.v1.ScreenQueryOptions.region:type_name -> sikuli.v1.Rect
	0,  // 14: sikuli.v1.ScreenQueryOptions.matcher_engine:type_name -> sikuli.v1.MatcherEngine
	4,  // 15: sikuli.v1.FindOnScreenRequest.pattern:type_name -> sikuli.v1.Pattern
	16, // 16: sikuli.v1.FindOnScreenRequest.opts:type_name -> sikuli.v1.ScreenQueryOptions
	4,  // 17: sikuli.v1.ExistsOnScreenRequest.pattern:type_name -> sikuli.v1.Pattern
	16, // 18: sikuli.v1.ExistsOnScreenRequest.opts:type_name -> sikuli.v1.ScreenQueryOptions
	5,  // 19: sikuli.v1.ExistsOnScreenResponse.match:type_name -> sikuli.v1.Match
	4,  // 20: sikuli.v1.WaitOnScreenRequest.pattern:type_name -> sikuli.v1.Pattern
	16, // 21: sikuli.v1.WaitOnScreenRequest.opts:type_name -> sikuli.v1.ScreenQueryOptions
	4,  // 22: sikuli.v1.ClickOnScreenRequest.pattern:type_name -> sikuli.v1.Pattern
	16, // 23: sikuli.v1.ClickOnScreenRequest.opts:type_name -> sikuli.v1.ScreenQueryOptions
	8,  // 24: sikuli.v1.ClickOnScreenRequest.click_opts:type_name -> sikuli.v1.InputOptions
	1,  // 25: sikuli.v1.ReadTextRequest.source:type_name -> sikuli.v1.GrayImage
	7,  // 26: sikuli.v1.ReadTextRequest.params:type_name -> sikuli.v1.OCRParams
	1,  // 27: sikuli.v1.FindTextRequest.source:type_name -> sikuli.v1.GrayImage
	7,  // 28: sikuli.v1.FindTextRequest.params:type_name -> sikuli.v1.OCRParams
	6,  // 29: sikuli.v1.FindTextResponse.matches:type_name -> sikuli.v1.TextMatch
	8,  // 30: sikuli.v1.MoveMouseRequest.opts:type_name -> sikuli.v1.InputOptions
	8,  // 31: sikuli.v1.ClickRequest.opts:type_name -> sikuli.v1.InputOptions
	8,  // 32: sikuli.v1.TypeTextRequest.opts:type_name -> sikuli.v1.InputOptions
	1,  // 33: sikuli.v1.ObserveRequest.source:type_name -> sikuli.v1.GrayImage
	3,  // 34: sikuli.v1.ObserveRequest.region:type_name -> sikuli.v1.Rect
	4,  // 35: sikuli.v1.ObserveRequest.pattern:type_name -> sikuli.v1.Pattern
	9,  // 36: sikuli.v1.ObserveRequest.opts:type_name -> sikuli.v1.ObserveOptions
	1,  // 37: sikuli.v1.ObserveChangeRequest.source:type_name -> sikuli.v1.GrayImage
	3,  // 38: sikuli.v1.ObserveChangeRequest.region:type_name -> sikuli.v1.Rect
	9,  // 39: sikuli.v1.ObserveChangeRequest.opts:type_name -> sikuli.v1.ObserveOptions
	12, // 40: sikuli.v1.ObserveResponse.events:type_name -> sikuli.v1.ObserveEvent
	10, // 41: sikuli.v1.AppActionRequest.opts:type_name -> sikuli.v1.AppOptions
	11, // 42: sikuli.v1.ListWindowsResponse.windows:type_name -> sikuli.v1.Window
	13, // 43: sikuli.v1.SikuliService.Find:input_type -> sikuli.v1.FindRequest
	13, // 44: sikuli.v1.SikuliService.FindAll:input_type -> sikuli.v1.FindRequest
	17, // 45: sikuli.v1.SikuliService.FindOnScreen:input_type -> sikuli.v1.FindOnScreenRequest
	18, // 46: sikuli.v1.SikuliService.ExistsOnScreen:input_type -> sikuli.v1.ExistsOnScreenRequest
	20, // 47: sikuli.v1.SikuliService.WaitOnScreen:input_type -> sikuli.v1.WaitOnScreenRequest
	21, // 48: sikuli.v1.SikuliService.ClickOnScreen:input_type -> sikuli.v1.ClickOnScreenRequest
	22, // 49: sikuli.v1.SikuliService.ReadText:input_type -> sikuli.v1.ReadTextRequest
	24, // 50: sikuli.v1.SikuliService.FindText:input_type -> sikuli.v1.FindTextRequest
	26, // 51: sikuli.v1.SikuliService.MoveMouse:input_type -> sikuli.v1.MoveMouseRequest
	27, // 52: sikuli.v1.SikuliService.Click:input_type -> sikuli.v1.ClickRequest
	28, // 53: sikuli.v1.SikuliService.TypeText:input_type -> sikuli.v1.TypeTextRequest
	29, // 54: sikuli.v1.SikuliService.Hotkey:input_type -> sikuli.v1.HotkeyRequest
	31, // 55: sikuli.v1.SikuliService.ObserveAppear:input_type -> sikuli.v1.ObserveRequest
	31, // 56: sikuli.v1.SikuliService.ObserveVanish:input_type -> sikuli.v1.ObserveRequest
	32, // 57: sikuli.v1.SikuliService.ObserveChange:input_type -> sikuli.v1.ObserveChangeRequest
	34, // 58: sikuli.v1.SikuliService.OpenApp:input_type -> sikuli.v1.AppActionRequest
	34, // 59: sikuli.v1.SikuliService.FocusApp:input_type -> sikuli.v1.AppActionRequest
	34, // 60: sikuli.v1.SikuliService.CloseApp:input_type -> sikuli.v1.AppActionRequest
	34, // 61: sikuli.v1.SikuliService.IsAppRunning:input_type -> sikuli.v1.AppActionRequest
	34, // 62: sikuli.v1.SikuliService.ListWindows:input_type -> sikuli.v1.AppActionRequest
	14, // 63: sikuli.v1.SikuliService.Find:output_type -> sikuli.v1.FindResponse
	15, // 64: sikuli.v1.SikuliService.FindAll:output_type -> sikuli.v1.FindAllResponse
	14, // 65: sikuli.v1.SikuliService.FindOnScreen:output_type -> sikuli.v1.FindResponse
	19, // 66: sikuli.v1.SikuliService.ExistsOnScreen:output_type -> sikuli.v1.ExistsOnScreenResponse
	14, // 67: sikuli.v1.SikuliService.WaitOnScreen:output_type -> sikuli.v1.FindResponse
	14, // 68: sikuli.v1.SikuliService.ClickOnScreen:output_type -> sikuli.v1.FindResponse
	23, // 69: sikuli.v1.SikuliService.ReadText:output_type -> sikuli.v1.ReadTextResponse
	25, // 70: sikuli.v1.SikuliService.FindText:output_type -> sikuli.v1.FindTextResponse
	30, // 71: sikuli.v1.SikuliService.MoveMouse:output_type -> sikuli.v1.ActionResponse
	30, // 72: sikuli.v1.SikuliService.Click:output_type -> sikuli.v1.ActionResponse
	30, // 73: sikuli.v1.SikuliService.TypeText:output_type -> sikuli.v1.ActionResponse
	30, // 74: sikuli.v1.SikuliService.Hotkey:output_type -> sikuli.v1.ActionResponse
	33, // 75: sikuli.v1.SikuliService.ObserveAppear:output_type -> sikuli.v1.ObserveResponse
	33, // 76: sikuli.v1.SikuliService.ObserveVanish:output_type -> sikuli.v1.ObserveResponse
	33, // 77: sikuli.v1.SikuliService.ObserveChange:output_type -> sikuli.v1.ObserveResponse
	30, // 78: sikuli.v1.SikuliService.OpenApp:output_type -> sikuli.v1.ActionResponse
	30, // 79: sikuli.v1.SikuliService.FocusApp:output_type -> sikuli.v1.ActionResponse
	30, // 80: sikuli.v1.SikuliService.CloseApp:output_type -> sikuli.v1.ActionResponse
	35, // 81: sikuli.v1.SikuliService.IsAppRunning:output_type -> sikuli.v1.IsAppRunningResponse
	36, // 82: sikuli.v1.SikuliService.ListWindows:output_type -> sikuli.v1.ListWindowsResponse
	63, // [63:83] is the sub-list for method output_type
	43, // [43:63] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_sikuli_v1_sikuli_proto_init() }
func file_sikuli_v1_sikuli_proto_init() {
	if File_sikuli_v1_sikuli_proto != nil {
		return
	}
	file_sikuli_v1_sikuli_proto_msgTypes[3].OneofWrappers = []any{}
	file_sikuli_v1_sikuli_proto_msgTypes[6].OneofWrappers = []any{}
	file_sikuli_v1_sikuli_proto_msgTypes[7].OneofWrappers = []any{}
	file_sikuli_v1_sikuli_proto_msgTypes[8].OneofWrappers = []any{}
	file_sikuli_v1_sikuli_proto_msgTypes[9].OneofWrappers = []any{}
	file_sikuli_v1_sikuli_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sikuli_v1_sikuli_proto_rawDesc), len(file_sikuli_v1_sikuli_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sikuli_v1_sikuli_proto_goTypes,
		DependencyIndexes: file_sikuli_v1_sikuli_proto_depIdxs,
		EnumInfos:         file_sikuli_v1_sikuli_proto_enumTypes,
		MessageInfos:      file_sikuli_v1_sikuli_proto_msgTypes,
	}.Build()
	File_sikuli_v1_sikuli_proto = out.File
	file_sikuli_v1_sikuli_proto_goTypes = nil
	file_sikuli_v1_sikuli_proto_depIdxs = nil
}
